In [167]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import warnings
import seaborn as sns

In [168]:
train=pd.read_csv("C:\\Users\\ADMIN\\Desktop\\Mtech_project\\project _xl_file\\classification.csv")

In [169]:
train.head()

taken date date of departure  no.of_days_left       Airline Aeroplane_ID  \
0  11/1/2019          1/9/2020               69  SpiceJet Ltd       SG 191   
1  11/1/2019          1/9/2020               69  SpiceJet Ltd       SG 197   
2  11/1/2019          1/9/2020               69  SpiceJet Ltd      SG 8719   
3  11/1/2019          1/9/2020               69  SpiceJet Ltd      SG 8905   
4  11/1/2019          1/9/2020               69  SpiceJet Ltd       SG 143   

      source destination Dep_Time Arrival_Time Duration  Cruidoilprice  \
0  New Delhi   Bengaluru     6:20         9:00  2h 40 m           56.2   
1  New Delhi   Bengaluru    16:35        19:25   2h 50m           56.2   
2  New Delhi   Bengaluru    18:25        21:15   2h 50m           56.2   
3  New Delhi   Bengaluru    19:55        22:55   2h 30m           56.2   
4  New Delhi   Bengaluru    21:45         0:25  2h 40 m           56.2   

   no_of_competitors on root  price   label  
0                          5    3732      1  
1                          5    3732      1  
2                          5    3732      1  
3                          5    3732      1  
4                          5    4157      1

In [170]:
train.drop(labels = 'date of departure', axis = 1, inplace = True)
train.drop(labels = 'no_of_competitors on root', axis = 1, inplace = True)
train.drop(labels = 'Airline', axis = 1, inplace = True)
train.drop(labels = 'source', axis = 1, inplace = True)
train.drop(labels = 'destination', axis = 1, inplace = True)
train.drop(labels = 'Aeroplane_ID', axis = 1, inplace = True)

In [171]:
train["isWeekend"] = ((pd.to_datetime(train["taken date"], format = '%m/%d/%Y').dt.dayofweek) // 5 == 1).astype(int)#doubt
train["Day_of_Week"] = pd.to_datetime(train["taken date"], format = '%m/%d/%Y').dt.day_name()
train["Day_Of_Journey"] = pd.to_datetime(train["taken date"], format = '%m/%d/%Y').dt.day
train["Month_of_Journey"] = pd.to_datetime(train["taken date"], format = '%m/%d/%Y').dt.month

In [87]:
train.drop(labels = 'taken date', axis = 1, inplace = True)

In [88]:
# cleaning duration column in train dataset
duration = list(train["Duration"])

for i in range(len(duration)) :
    if len(duration[i].split()) != 2:
        if 'h' in duration[i] :
            duration[i] = duration[i].strip() + ' 0m'
        elif 'm' in duration[i] :
            duration[i] = '0h {}'.format(duration[i].strip())

dur_hours = []
dur_minutes = []  
dur_seconds = []
for i in range(len(duration)) :
    dur_minutes.append(int(duration[i].split()[0][:-1])*60 + int(duration[i].split()[1][:-1]))
    dur_seconds.append(int(duration[i].split()[0][:-1])*60*60 + int(duration[i].split()[1][:-1])*60)
train["Duration_minutes"] = dur_minutes
train.drop(["Duration"], axis=1, inplace = True)

In [89]:
#Cleaning Departure and Arrival Times
# Training Set
train['Depart_Time_Hour'] = pd.to_datetime(train.Dep_Time).dt.hour
train['Depart_Time_Minutes'] = pd.to_datetime(train.Dep_Time).dt.minute
train.drop(labels = 'Dep_Time', axis = 1, inplace = True)
train['Arr_Time_Hour'] = pd.to_datetime(train.Arrival_Time).dt.hour
train['Arr_Time_Minutes'] = pd.to_datetime(train.Arrival_Time).dt.minute
train.drop(labels = 'Arrival_Time', axis = 1, inplace = True)

In [90]:
train.Day_of_Week.replace(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'], [1,2,3,4,5,6,7], inplace=True)
train["Day_of_Week"] = train["Day_of_Week"].astype(int)

In [91]:
bins = [-1, 3, 6, 9, 12, 15, 18, 21, 24]
labels = ['late evening','magical hours','early morning','morning','early afternoon','afternoon','early evening','evening']
train['part_of_day'] = pd.cut(train['Depart_Time_Hour'], bins=bins, labels=labels)

In [92]:
train.part_of_day.replace(['late evening','magical hours','early morning','morning','early afternoon','afternoon','early evening','evening'], [6,7, 0,1, 2, 3, 4,5], inplace=True)

In [93]:
train.drop(labels = 'isWeekend', axis = 1, inplace = True)

In [94]:
train.head()

no.of_days_left  Cruidoilprice  price   label  Day_of_Week  Day_Of_Journey  \
0               69           56.2    3732      1            5               1   
1               69           56.2    3732      1            5               1   
2               69           56.2    3732      1            5               1   
3               69           56.2    3732      1            5               1   
4               69           56.2    4157      1            5               1   

   Month_of_Journey  Duration_minutes  Depart_Time_Hour  Depart_Time_Minutes  \
0                11               124                 6                   20   
1                11               170                16                   35   
2                11               170                18                   25   
3                11               150                19                   55   
4                11               124                21                   45   

   Arr_Time_Hour  Arr_Time_Minutes  part_of_day  
0              9                 0            7  
1             19                25            3  
2             21                15            3  
3             22                55            4  
4              0                25            4

In [95]:
#train.drop(labels = 'Unnamed: 14', axis = 1, inplace = True)

In [96]:
#train.drop(labels = 'Unnamed: 15', axis = 1, inplace = True)

In [97]:
#train.drop(labels = 'Unnamed: 16', axis = 1, inplace = True)
#train.drop(labels = 'Unnamed: 17', axis = 1, inplace = True)
#train.drop(labels = 'Unnamed: 18', axis = 1, inplace = True)

In [98]:
train.head()

no.of_days_left  Cruidoilprice  price   label  Day_of_Week  Day_Of_Journey  \
0               69           56.2    3732      1            5               1   
1               69           56.2    3732      1            5               1   
2               69           56.2    3732      1            5               1   
3               69           56.2    3732      1            5               1   
4               69           56.2    4157      1            5               1   

   Month_of_Journey  Duration_minutes  Depart_Time_Hour  Depart_Time_Minutes  \
0                11               124                 6                   20   
1                11               170                16                   35   
2                11               170                18                   25   
3                11               150                19                   55   
4                11               124                21                   45   

   Arr_Time_Hour  Arr_Time_Minutes  part_of_day  
0              9                 0            7  
1             19                25            3  
2             21                15            3  
3             22                55            4  
4              0                25            4

In [99]:
X=train.drop('label',axis=1)
y=train['label']

In [100]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X

C:\Users\ADMIN\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int32, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\ADMIN\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int32, int64, float64 were all converted to float64 by StandardScaler.
  


array([[ 1.71740195, -1.25931594, -1.21729911, ..., -0.69058708,
        -1.85872915,  1.4625316 ],
       [ 1.71740195, -1.25931594, -1.21729911, ...,  0.75442529,
        -0.43273256, -0.29268149],
       [ 1.71740195, -1.25931594, -1.21729911, ...,  1.04342776,
        -1.0031312 , -0.29268149],
       ...,
       [-1.68943498,  0.28315483,  2.54611675, ...,  0.60992405,
         0.99326402, -0.29268149],
       [-1.68943498,  0.28315483,  1.98401339, ...,  0.89892653,
        -0.43273256, -0.29268149],
       [-1.68943498,  0.28315483,  1.19248008, ...,  0.32092158,
         0.99326402, -0.73148476]])

In [101]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (2404, 12) (2404,)
Test set: (602, 12) (602,)


In [102]:
train.columns

Index(['no.of_days_left', 'Cruidoilprice', 'price ', 'label', 'Day_of_Week',
       'Day_Of_Journey', 'Month_of_Journey', 'Duration_minutes',
       'Depart_Time_Hour', 'Depart_Time_Minutes', 'Arr_Time_Hour',
       'Arr_Time_Minutes', 'part_of_day'],
      dtype='object')

# 1.LOGISTIC REGRESSION

In [103]:
from sklearn.linear_model import LogisticRegression

In [104]:
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

C:\Users\ADMIN\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [105]:
predictions=classifier.predict(X_test)

In [106]:
#predictions

In [107]:
y_test[0:5]

573     1
1243    0
2977    0
1618    0
1002    0
Name: label, dtype: int64

In [108]:
classifier.score(X,y)

0.7870924817032602

In [109]:
from sklearn.metrics import classification_report,confusion_matrix

In [110]:
print(confusion_matrix(y_test,predictions))

[[276  51]
 [ 84 191]]


In [111]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.77      0.84      0.80       327
           1       0.79      0.69      0.74       275

   micro avg       0.78      0.78      0.78       602
   macro avg       0.78      0.77      0.77       602
weighted avg       0.78      0.78      0.77       602



yhat_prob =  classifier.predict_proba(X_test)
yhat_prob
#predict_proba returns estimates for all classes, ordered by the label of classes.
#So, the first column is the probability of class 1, P(Y=1|X), and second column is probability of class 0, P(Y=0|X):

In [112]:
yhat_prob = classifier.predict_proba(X_test) 
yhat_prob



array([[2.17771965e-01, 7.82228035e-01],
       [8.96263577e-01, 1.03736423e-01],
       [9.99861912e-01, 1.38088173e-04],
       ...,
       [6.55985851e-01, 3.44014149e-01],
       [4.31595227e-01, 5.68404773e-01],
       [8.37250789e-01, 1.62749211e-01]])

In [113]:
train.columns

Index(['no.of_days_left', 'Cruidoilprice', 'price ', 'label', 'Day_of_Week',
       'Day_Of_Journey', 'Month_of_Journey', 'Duration_minutes',
       'Depart_Time_Hour', 'Depart_Time_Minutes', 'Arr_Time_Hour',
       'Arr_Time_Minutes', 'part_of_day'],
      dtype='object')

In [114]:
classifier.predict([[30,56,5200,4,5,11,150,6,30,8,50,5]])

array([0], dtype=int64)

In [115]:
classifier.predict_proba([[30,56,5200,4,5,11,150,6,30,8,50,5]])

array([[1., 0.]])

In [116]:
classifier.predict_proba([[60,56,3500,4,5,11,150,6,30,8,50,5]])

array([[1.00000000e+000, 7.52197886e-234]])

In [117]:
#coeff_df = pd.DataFrame(classifier.coef_,X.columns,columns=['Coefficient'])
#coeff_df

In [118]:
classifier.predict([[60,56,3500,4,5,11,150,6,30,8,50,5]])

array([0], dtype=int64)

In [119]:
#print(classifier.intercept_)

In [120]:

#classifier.coef_

In [121]:
#classifier[[]]

# 2.DECISION TREE

In [122]:
from sklearn.tree import DecisionTreeClassifier

In [123]:
dtree=DecisionTreeClassifier()
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [124]:
predictions=dtree.predict(X_test)

In [125]:
predictions[0:5]

array([1, 0, 0, 0, 0], dtype=int64)

In [126]:
from sklearn.metrics import classification_report,confusion_matrix

In [127]:
print(confusion_matrix(y_test,predictions))

[[327   0]
 [  0 275]]


In [128]:
print(classification_report(y_test,predictions))          # model is over fitted here.

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       327
           1       1.00      1.00      1.00       275

   micro avg       1.00      1.00      1.00       602
   macro avg       1.00      1.00      1.00       602
weighted avg       1.00      1.00      1.00       602



In [129]:

dtree.score(X,y)

1.0

In [130]:

dtree.predict([[30,56,5200,4,5,11,150,6,30,8,50,5]])

array([1], dtype=int64)

In [131]:
dtree.predict([[30,56,0,4,5,11,150,6,30,8,50,5]])

array([1], dtype=int64)

#  3.SVM

In [132]:
from sklearn.svm import SVC

In [133]:
model=SVC(kernel='linear')

In [134]:
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [135]:

predictions=model.predict(X_test)

In [136]:
predictions[0:10]

array([1, 0, 0, 0, 1, 0, 1, 1, 1, 0], dtype=int64)

In [137]:
from sklearn.metrics import classification_report,confusion_matrix

In [138]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.76      0.83      0.80       327
           1       0.78      0.69      0.73       275

   micro avg       0.77      0.77      0.77       602
   macro avg       0.77      0.76      0.76       602
weighted avg       0.77      0.77      0.77       602



In [139]:
model.score(X,y)

0.7827677977378577

In [140]:
train.columns

Index(['no.of_days_left', 'Cruidoilprice', 'price ', 'label', 'Day_of_Week',
       'Day_Of_Journey', 'Month_of_Journey', 'Duration_minutes',
       'Depart_Time_Hour', 'Depart_Time_Minutes', 'Arr_Time_Hour',
       'Arr_Time_Minutes', 'part_of_day'],
      dtype='object')

In [141]:
#yhat_prob3 = model.p3redict_proba(X_test) 
#yhat_prob3

# 4.KNN

In [142]:

from sklearn.neighbors import KNeighborsClassifier

In [143]:

knn=KNeighborsClassifier(n_neighbors=3)

In [144]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [145]:
pred=knn.predict(X_test)

In [146]:
pred[0:10]

array([1, 0, 0, 0, 1, 0, 1, 1, 1, 0], dtype=int64)

In [147]:
from sklearn.metrics import classification_report,confusion_matrix

In [148]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.76      0.83      0.80       327
           1       0.78      0.69      0.73       275

   micro avg       0.77      0.77      0.77       602
   macro avg       0.77      0.76      0.76       602
weighted avg       0.77      0.77      0.77       602



In [149]:
knn.score(X,y)

0.9660678642714571

In [150]:
knn.predict([[60,56,3500,4,5,11,150,6,30,8,50,5]])

array([0], dtype=int64)

In [151]:
knn.predict([[30,56,0,4,5,11,150,6,30,8,50,5]])

array([0], dtype=int64)

 # 5.RANDOMFOREST

In [152]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=18)
rfc.fit(X_train,y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=18, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [153]:
pred=rfc.predict(X_test)

In [154]:
pred[0:10]

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int64)

In [155]:
from sklearn.metrics import classification_report,confusion_matrix

In [156]:

print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.76      0.83      0.80       327
           1       0.78      0.69      0.73       275

   micro avg       0.77      0.77      0.77       602
   macro avg       0.77      0.76      0.76       602
weighted avg       0.77      0.77      0.77       602



In [157]:
knn.predict([[60,56,3500,4,5,11,150,6,30,8,50,5]])

array([0], dtype=int64)

In [158]:
knn.predict([[30,56,0,4,5,11,150,6,30,8,50,5]])

array([0], dtype=int64)

In [159]:
knn.score(X,y)

0.9660678642714571

# k-fold cross validation

In [160]:
from sklearn.model_selection import cross_val_score

In [161]:
k1=cross_val_score(LogisticRegression(random_state=0), X, y,cv=3)

C:\Users\ADMIN\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ADMIN\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ADMIN\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [162]:
k1

array([0.52442672, 0.33033932, 0.5984016 ])

In [163]:
k1.mean()

0.4843892131997875

In [164]:
k2=cross_val_score(RandomForestClassifier(n_estimators=18), X, y,cv=10)

In [165]:
k2

array([0.71428571, 1.        , 1.        , 1.        , 0.9269103 ,
       0.88704319, 1.        , 0.8538206 , 0.74247492, 0.70568562])

In [166]:
k2.mean()             #final accuracy

0.883022033578151